# Generated by Django 5.2.5 on 2025-09-19 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agronomist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('specialization', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, help_text='Total Area of Farm in Donum', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agronomists', models.ManyToManyField(related_name='managed_farms', to='rootsPlusApp.agronomist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='rootsPlusApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(blank=True, max_length=60, null=True)),
                ('yield_amount', models.FloatField(blank=True, help_text='Total yield in tons', null=True)),
                ('crops_count', models.IntegerField(blank=True, help_text='Number of crops in the farm', null=True)),
                ('average_yield_per_donum', models.FloatField(blank=True, help_text='Average yield per donum (tons/donum)', null=True)),
                ('activity_score', models.FloatField(blank=True, null=True)),
                ('cost_efficiency', models.FloatField(blank=True, null=True)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agronomist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='rootsPlusApp.agronomist')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='rootsPlusApp.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(blank=True, max_length=60, null=True)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('crop_area', models.DecimalField(blank=True, decimal_places=2, help_text='Crop Area in Donum', max_digits=10, null=True)),
                ('yield_per_donum', models.DecimalField(blank=True, decimal_places=2, help_text='Yield per donum (tons/donum)', max_digits=10, null=True)),
                ('total_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Total yield in tons', max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='rootsPlusApp.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(blank=True, help_text='Soil type (e.g., Clay, Sandy, Loamy)', max_length=50, null=True)),
                ('soil_salinity', models.DecimalField(blank=True, decimal_places=2, help_text='Soil salinity (dS/m)', max_digits=5, null=True)),
                ('soil_ph', models.DecimalField(blank=True, decimal_places=2, help_text='Soil pH', max_digits=4, null=True)),
                ('water_salinity', models.DecimalField(blank=True, decimal_places=2, help_text='Water salinity (dS/m)', max_digits=5, null=True)),
                ('analysis_date', models.DateField(blank=True, help_text='Date of analysis', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='rootsPlusApp.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(blank=True, max_length=60, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agronomist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='rootsPlusApp.agronomist')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='rootsPlusApp.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='rootsPlusApp.farm')),
            ],
        ),
        migrations.CreateModel(
            name='FarmReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(blank=True, max_length=60, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='rootsPlusApp.farm')),
            ],
        ),
    ]
