# Generated by Django 5.2.5 on 2025-09-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootsPlusApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='yield_per_donum',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='average_yield_per_donum',
        ),
        migrations.AddField(
            model_name='crop',
            name='yield_per_dunum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yield per dunum (tons/dunum)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='average_yield_per_dunum',
            field=models.FloatField(blank=True, help_text='Average yield per dunum (tons/dunum)', null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Crop Area in dunum', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='total_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Area of Farm in dunum', max_digits=10, null=True),
        ),
    ]
