# Generated by Django 5.2.5 on 2025-09-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rootsPlusApp', '0003_user_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='crop_type',
            new_name='crop_name',
        ),
    ]
