# Generated by Django 5.2.5 on 2025-09-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootsPlusApp', '0004_rename_crop_type_crop_crop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('irrigation', 'Irrigation'), ('fertilization', 'Fertilization'), ('harvest', 'Harvest'), ('inspection', 'Inspection'), ('pest_control', 'Pest Control'), ('planting', 'Planting'), ('other', 'other')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='total_area',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Total Area of Farm in dunum', max_digits=10, null=True),
        ),
    ]
