# Generated by Django 5.2.5 on 2025-09-20 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootsPlusApp', '0005_alter_activity_activity_type_alter_farm_total_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmreport',
            name='file',
        ),
        migrations.AddField(
            model_name='farmreport',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theReports', to='rootsPlusApp.agronomist'),
        ),
        migrations.AddField(
            model_name='farmreport',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmreport',
            name='status',
            field=models.CharField(default='Draft', max_length=20),
        ),
    ]
