# Generated by Django 5.2.5 on 2025-09-20 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootsPlusApp', '0006_remove_farmreport_file_farmreport_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmreport',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theReports', to='rootsPlusApp.agronomist'),
        ),
    ]
