# Generated by Django 5.2.5 on 2025-09-20 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootsPlusApp', '0009_alter_farmreport_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmreport',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theReports', to='rootsPlusApp.agronomist'),
        ),
    ]
