# Generated by Django 5.2.5 on 2025-09-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rootsPlusApp', '0011_agronomist_avatar_user_avatar_post_comment_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='agronomist',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_agronomist',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
